### ISSUE TITLE
Hello, can you provide the model obj file

### ISSUE THREAD

**Issue by qianqian321** [sheeaza/qjhs#5]

**Comment by sheeaza** [comment]
Sorry the obj file is missing, but you can make one by 3ds max

**Comment by qianqian321** [comment]
请问您这个代码实现的效果就是演示视频里那样么

**Comment by sheeaza** [comment]
是的


在 2023年3月27日，10:08，qianqian321 ***@***.***> 写道：

﻿

请问您这个代码实现的效果就是演示视频里那样么

**Comment by qianqian321** [comment]
请问这个obj文件该怎么写呢，有参考吗，谢谢

**Comment by qianqian321** [comment]
已收到，我会尽快回复。
